services:
  ldap:
    image: osixia/openldap:1.5.0
    command: --copy-service
    container_name: ldap
    environment:
      - LDAP_ORGANISATION=Hogwarts school
      - LDAP_DOMAIN=hogwarts.com
      - LDAP_BASE_DN=dc=hogwarts,dc=com
      - LDAP_ADMIN_PASSWORD=password
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom